### ISSUE TITLE
Mirroring is not working

### ISSUE THREAD

**Issue by bpipi** [01org/wds#154]
Hi,
    I am using raspberry pi with raspbian jessie os.
    I have successfully compiled the dependencies but sometimes after connection success the device will show segmentation fault, sometimes after connection success wds device wont mirror any screen, sometimes it will show following error
error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 0.36.1
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null).

I have tried this for so many times, and everytime I run the sink-test I am getting new error. Can you please tell help me with this?

**Comment by jku** [comment]
I realize it's frustrating when you are seeing multiple issues. Still it would be good to concentrate on one issue per bug report. 

For the segfault: can you run sink-test under gdb and get a backtrace?

**Comment by bpipi** [comment]
Hi, 
I run sink-test under gdb and got following backtrace for the segmentation fault.

root@raspberrypi:/home/pi/wds/sink# gdb sink-test
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sink-test...done.
(gdb) 
(gdb) b main
Breakpoint 1 at 0x34e30
(gdb) r
Starting program: /home/pi/wds/sink/sink-test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Breakpoint 1, 0x00034e30 in main ()
(gdb) step
Single stepping until exit from function main,
which has no line number information.
gst_init_get_option_group () at gst.c:289
289 gst.c: No such file or directory.
(gdb) 
226 in gst.c
(gdb) 
289 in gst.c
(gdb) n
290 in gst.c
(gdb) n
289 in gst.c
(gdb) n
290 in gst.c
(gdb) n
289 in gst.c
(gdb) n
290 in gst.c
(gdb) s
289 in gst.c
(gdb) s
291 in gst.c
(gdb) s
289 in gst.c
(gdb) s
291 in gst.c
(gdb) s
294 in gst.c
(gdb) s
295 in gst.c
(gdb) s
301 in gst.c
(gdb) s
0x00034eec in main ()
(gdb) s
Single stepping until exit from function main,
which has no line number information.

Registering Wifi Display with IE 00000600111C440032 [New Thread 0xb67363e0 (LWP 1211)] [New Thread 0xb5dff3e0 (LWP 1212)] [New Thread 0xb53ff3e0 (LWP 1213)]
New peer: Shrikant
Connecting to source at 192.168.0.2:7236 ** Message: Trying to connect... [Thread 0xb67363e0 (LWP 1211) exited] ** Message: connection success to: 192.168.0.2 [New Thread 0xb67363e0 (LWP 1283)]
** (sink-test:1208): WARNING *: * GET_PARAMETER: Ignoring unsupported property 'wd_initial_buffer'.
[New Thread 0xb48a53e0 (LWP 1323)]
[New Thread 0xb40333e0 (LWP 1324)]
[New Thread 0xb35253e0 (LWP 1325)]
[New Thread 0xb2d253e0 (LWP 1326)]
[New Thread 0xb25253e0 (LWP 1327)]
[New Thread 0xb1bff3e0 (LWP 1328)]
[New Thread 0xb0f283e0 (LWP 1329)]
[New Thread 0xb07283e0 (LWP 1330)]
[New Thread 0xaff283e0 (LWP 1331)]
[New Thread 0xaf5ff3e0 (LWP 1332)]
[Thread 0xb07283e0 (LWP 1330) exited]
[New Thread 0xb07283e0 (LWP 1333)]
[New Thread 0xaacf13e0 (LWP 1334)]
[New Thread 0xaa47d3e0 (LWP 1335)]
[New Thread 0xa9aff3e0 (LWP 1336)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa9aff3e0 (LWP 1336)]
0x00000000 in ?? ()
(gdb) backtrace
#0 0x00000000 in ?? ()
#1 0xb364fcc8 in _gen_texture_full (context=, data=0xaf5fe850) at gstglutils.c:167
#2 0xb364dbe0 in _run_message_sync (message=0xaf5fe7dc) at gstglwindow.c:353
#3 0xb3652970 in _run_message (message=0xb5ed3010) at gstglwindow_dispmanx_egl.c:190
#4 0xb6c941c4 in g_main_context_dispatch () from /lib/arm-linux-gnueabihf/libglib-2.0.so.0
Cannot access memory at address 0x1
#5 0xb6c94588 in ?? () from /lib/arm-linux-gnueabihf/libglib-2.0.so.0
Cannot access memory at address 0x1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

Please help me with this?

Thanks
